-- Customer support tickets with private diagnostic attachments.

create table public.support_tickets (
  id uuid primary key default gen_random_uuid(),
  ticket_number bigint generated by default as identity unique,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  created_by uuid not null references public.profiles(id) on delete restrict,
  category text not null check (category in ('INTERFACE', 'TELEGRAM', 'DATA', 'QUESTION', 'IDEA', 'OTHER')),
  priority text not null default 'NORMAL' check (priority in ('NORMAL', 'HIGH', 'BLOCKER')),
  status text not null default 'OPEN' check (status in ('OPEN', 'IN_PROGRESS', 'WAITING_CUSTOMER', 'RESOLVED', 'CLOSED')),
  subject text not null check (char_length(trim(subject)) between 5 and 120),
  description text not null check (char_length(trim(description)) between 15 and 4000),
  steps_to_reproduce text check (steps_to_reproduce is null or char_length(steps_to_reproduce) <= 2000),
  contact text check (contact is null or char_length(contact) <= 160),
  page_url text check (page_url is null or char_length(page_url) <= 1000),
  user_agent text check (user_agent is null or char_length(user_agent) <= 1000),
  device_timezone text check (device_timezone is null or char_length(device_timezone) <= 100),
  app_version text check (app_version is null or char_length(app_version) <= 100),
  technical_context jsonb not null default '{}'::jsonb check (jsonb_typeof(technical_context) = 'object'),
  attachment_bucket text,
  attachment_path text,
  attachment_filename text,
  attachment_content_type text,
  attachment_size_bytes bigint check (attachment_size_bytes is null or attachment_size_bytes between 1 and 5242880),
  response_text text check (response_text is null or char_length(response_text) <= 4000),
  responded_at timestamptz,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, organization_id),
  check ((attachment_path is null and attachment_bucket is null) or (attachment_path is not null and attachment_bucket is not null)),
  check ((status in ('RESOLVED', 'CLOSED') and resolved_at is not null) or status not in ('RESOLVED', 'CLOSED'))
);

create index support_tickets_org_created_idx on public.support_tickets (organization_id, created_at desc);
create index support_tickets_status_idx on public.support_tickets (status, priority, created_at);

alter table public.support_tickets enable row level security;

create policy support_tickets_select_creator_or_owner on public.support_tickets for select using (
  created_by = auth.uid()
  or public.has_org_role(organization_id, array['OWNER']::public.organization_role[])
);

create policy support_tickets_insert_member on public.support_tickets for insert with check (
  created_by = auth.uid() and public.is_active_member(organization_id)
);

create or replace function public.prepare_support_ticket_update()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.response_text is distinct from old.response_text and new.response_text is not null then
    new.responded_at := now();
  end if;
  if new.status in ('RESOLVED', 'CLOSED') and old.status not in ('RESOLVED', 'CLOSED') then
    new.resolved_at := now();
  elsif new.status not in ('RESOLVED', 'CLOSED') then
    new.resolved_at := null;
  end if;
  return new;
end;
$$;

create trigger support_tickets_prepare_update
before update on public.support_tickets
for each row execute procedure public.prepare_support_ticket_update();

create trigger support_tickets_set_updated_at
before update on public.support_tickets
for each row execute procedure public.set_updated_at();

grant select, insert on table public.support_tickets to authenticated;
grant usage, select on sequence public.support_tickets_ticket_number_seq to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'support-attachments',
  'support-attachments',
  false,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create policy support_attachments_insert_own on storage.objects for insert to authenticated with check (
  bucket_id = 'support-attachments'
  and (storage.foldername(name))[1] is not null
  and (storage.foldername(name))[2] = auth.uid()::text
  and public.is_active_member(((storage.foldername(name))[1])::uuid)
);

create policy support_attachments_delete_own on storage.objects for delete to authenticated using (
  bucket_id = 'support-attachments'
  and (storage.foldername(name))[2] = auth.uid()::text
);

alter publication supabase_realtime add table public.support_tickets;
